spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoteldb
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

# ⭐⭐⭐ CONFIGURATION CIRCUIT BREAKER ⭐⭐⭐
resilience4j:
  circuitbreaker:
    instances:
      locationService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        register-health-indicator: true
        allow-health-indicator-to-fail: true
