server:
  port: 8080

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:h2:mem:hoteldb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
